externalURL: https://harbor.local
expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.local
    annotations:
      kubernetes.io/ingress.class: nginx

# 주석 처리된 실제 도메인 설정 예시
# externalURL: https://harbor.example.com
# expose:
#   type: ingress
#   ingress:
#     hosts:
#       core: harbor.example.com
#     annotations:
#       kubernetes.io/ingress.class: nginx
